# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- example

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x
      echo 'bout to get up in some Java'
      git clone https://github.com/mojavelinux/jboss-as-quickstart.git
      cd jboss-as-quickstart/helloworld

- task: Maven@3
  inputs:
    mavenPomFile: 'jboss-as-quickstart/helloworld/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishPipelineArtifact@1
  inputs:
    path: jboss-as-quickstart/helloworld/target/jboss-as-helloworld.war
    artifact: HelloWorld.war

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: rhythmic-test-docker-registry-endpoint

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: jboss-hello-world
    tags: |
      latest