---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloWorld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloWorld
  template:
    metadata:
      labels:
        app: helloWorld
    spec:
      containers:
      - name: nginx
        image: manualTest.azurecr.io/jboss-hello-world
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /hello
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /hello
            port: http
            
        resources:
          limits:
            cpu: 256
            memory: 256

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloWorld
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /hello
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: helloworld
          servicePort: http
